@BaseUrl_Https = https://localhost:7126
@BaseUrl_Http = http://localhost:5296

GET {{BaseUrl_Https}}/weather/forecast
Accept: application/json

### Func<>

GET {{BaseUrl_Https}}/weather/forecast2
Accept: application/json

### DI passing to method
